- name: Install racoon
  ansible.builtin.apt:
    pkg:
      - ipsec-tools
      - net-tools
      - ntpdate
      - racoon
      - rsync
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version | int <= 9

- name: Install strongswan
  ansible.builtin.apt:
    pkg:
      - libstrongswan-extra-plugins
      - libstrongswan-standard-plugins
      - net-tools
      - ntpdate
      - rsync
      - strongswan
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version | int >= 10
